export const COACHES = {
  fitzgerald: {
    id: 'fitzgerald',
    name: 'Jason Fitzgerald',
    role: 'Strength & structure',
    color: '#BA7517',
    url: 'https://strengthrunning.com',
  },
  bennett: {
    id: 'bennett',
    name: 'Coach Bennett',
    role: 'Effort & consistency',
    color: '#185FA5',
    url: 'https://www.nike.com/nrc-app',
  },
  parkes: {
    id: 'parkes',
    name: 'Ben Parkes',
    role: 'Half marathon progression',
    color: '#0F6E56',
    url: 'https://www.youtube.com/@BenParkes',
  },
  mcmillan: {
    id: 'mcmillan',
    name: 'Greg McMillan',
    role: 'Your exact training paces',
    color: '#534AB7',
    url: 'https://www.mcmillanrunning.com',
  },
  mta: {
    id: 'mta',
    name: 'Angie Spencer',
    role: 'Race mindset & long run strategy',
    color: '#993C1D',
    url: 'https://www.marathontrainingacademy.com/podcast',
  },
}

export const PHILOSOPHY_CARDS = [
  {
    id: 'easy_run',
    title: 'Easy Run Days',
    sessions: 'Monday / Wednesday recovery runs',
    coaches: ['fitzgerald', 'bennett'],
    quote: "If you can't hold a full conversation, you're going too fast. Easy runs build your aerobic base — the foundation everything else sits on.",
    quoteCoach: 'fitzgerald',
    tip: "Enjoyment is the metric. If it feels embarrassingly slow, it's probably right.",
    tipCoach: 'bennett',
    link: 'https://strengthrunning.com/easy-running/',
  },
  {
    id: 'tempo',
    title: 'Tempo Runs',
    sessions: 'Wednesday quality sessions',
    coaches: ['parkes', 'mcmillan'],
    quote: "Tempo pace is comfortably hard — 3-4 words per breath, not full sentences. Most beginners run it too fast and pay for it 20 minutes in.",
    quoteCoach: 'parkes',
    tip: "Use your McMillan threshold pace. It's calculated from YOUR fitness, not someone else's. Don't guess.",
    tipCoach: 'mcmillan',
    link: 'https://www.mcmillanrunning.com/article/the-tempo-run/',
  },
  {
    id: 'long_run',
    title: 'Long Runs',
    sessions: 'Saturday — odd weeks',
    coaches: ['mta', 'parkes'],
    quote: "The long run is the most important session of the week. Run it easy. If you're racing the long run, you're training wrong.",
    quoteCoach: 'mta',
    tip: "Add distance by no more than 10% per week. The injury you avoid IS the training you gain.",
    tipCoach: 'parkes',
    link: 'https://www.marathontrainingacademy.com/long-run',
  },
  {
    id: 'stations',
    title: 'Hyrox Station Sessions',
    sessions: 'Monday',
    coaches: ['fitzgerald'],
    quote: "Strength is not cross-training for runners — it IS the training. Heavy loaded work signals your body to keep muscle while you burn fat.",
    quoteCoach: 'fitzgerald',
    tip: "Always practice stations after running, never fresh. The skill is the transition, not the station alone.",
    tipCoach: 'fitzgerald',
    link: 'https://strengthrunning.com/strength-training-for-runners/',
  },
  {
    id: 'hyrox_sim',
    title: 'Hyrox Simulation Days',
    sessions: 'Saturday — even weeks',
    coaches: ['mta', 'fitzgerald'],
    quote: "Nothing prepares you for race day like rehearsing race day. Do at least 2 full simulations before you toe the line.",
    quoteCoach: 'mta',
    tip: "Start conservative. The runners who blow up at station 5 all had one thing in common — they ran the first 4km too fast.",
    tipCoach: 'mta',
    link: null,
  },
]

export const RESOURCES = [
  {
    id: 'fitz-easy',
    coach: 'fitzgerald',
    title: 'Why easy runs should be easy',
    summary: 'The science behind Zone 2 and why running slow makes you faster long-term.',
    url: 'https://strengthrunning.com/easy-running/',
    format: 'Article',
  },
  {
    id: 'fitz-strength',
    coach: 'fitzgerald',
    title: 'Strength training for runners',
    summary: 'Exactly the lifts distance runners need — and why heavy compound work beats light isolation every time.',
    url: 'https://strengthrunning.com/strength-training-for-runners/',
    format: 'Article',
  },
  {
    id: 'bennett-app',
    coach: 'bennett',
    title: 'Guided runs library',
    summary: 'Audio-coached runs for every session type — easy, tempo, long run. Download the app and use on every training day.',
    url: 'https://www.nike.com/nrc-app',
    format: 'App / Audio',
  },
  {
    id: 'parkes-playlist',
    coach: 'parkes',
    title: 'Half marathon training for beginners',
    summary: 'Ben documents his own training while coaching you. Clear, no-jargon breakdowns of how to progress from 5K to half marathon.',
    url: 'https://www.youtube.com/@BenParkes',
    format: 'Video',
  },
  {
    id: 'parkes-race',
    coach: 'parkes',
    title: 'How to run your first half marathon',
    summary: 'Race day execution, pacing strategy, and what to expect at each km.',
    url: 'https://www.youtube.com/@BenParkes',
    format: 'Video',
  },
  {
    id: 'mcmillan-calc',
    coach: 'mcmillan',
    title: 'McMillan Pace Calculator',
    summary: 'The gold standard pace calculator used by recreational runners and Olympians. Enter any race result, get all your training paces.',
    url: 'https://www.mcmillanrunning.com/mcmillan-pace-calculator/',
    format: 'Tool',
  },
  {
    id: 'mcmillan-tempo',
    coach: 'mcmillan',
    title: 'The Tempo Run explained',
    summary: 'What tempo pace actually feels like, why it works, and how to execute it.',
    url: 'https://www.mcmillanrunning.com/article/the-tempo-run/',
    format: 'Article',
  },
  {
    id: 'mta-podcast',
    coach: 'mta',
    title: 'MTA Podcast',
    summary: '600+ episodes covering training, nutrition, race strategy and mindset. Best listened to on long run Saturdays.',
    url: 'https://www.marathontrainingacademy.com/podcast',
    format: 'Podcast',
  },
  {
    id: 'mta-longrun',
    coach: 'mta',
    title: 'Long run strategy guide',
    summary: 'Why the long run is the cornerstone of any distance training plan and how to structure it correctly as a beginner.',
    url: 'https://www.marathontrainingacademy.com/long-run',
    format: 'Article',
  },
]
